- README.md
Hi!
TestContainers' docs were migrated to Gitbook and the new link is: https://www.testcontainers.org
> Use new documentation links

- gradle.properties
Upgraded testcontainers version and bumped minor version.
Note: when testing with the most recent version of docker for mac [this bug](https://github.com/testcontainers/testcontainers-java/issues/293) cause by [this other bug](https://github.com/docker-java/docker-java/issues/806) prevented testcontainers from working correctly. After manually pulling the images and then commenting out `~/.docker/config.json` would testcontainers and the tests work. Once docker-java gets fixed this workaround won't be needed anymore.
Fixes #2
> Upgrade Testcontainers 1.2.0

- src/main/scala/com/dimafeng/testcontainers/TestContainer.scala
We wanted to ignore integration tests, but noticed that docker containers are still started, even though all tests have been ignored.
This patch fixes the `ForAllTestContainer` trait to not start containers in the case that all tests are ignored
)
> Don't start container when all tests are ignored

- README.md
- build.sbt
- src/main/scala/com/dimafeng/testcontainers/MultipleContainers.scala
- src/test/scala/com/dimafeng/testcontainers/MultipleContainersSpec.scala
- version.sbt
Main points:
* Removed `shapeless` dependency.
* Added implicit conversion to `LazyContainer`. This gives you a possibility to not wrap your containers into the `LazyContainer` manually.
* `MultipleContainers.apply` now receives `LazyContainer[_]*` type. Together with the previous point, it makes usage experience of `MultipleContainers` more smooth.
```scala
// before
lazy val pgContainer = PostgreSQLContainer()
lazy val appContainer = AppContainer(pgContainer.jdbcUrl, pgContainer.username, pgContainer.password)
val containers = MultipleContainers(LazyContainer(pgContainer), LazyContainer(appContainer))
//after
lazy val pgContainer = PostgreSQLContainer()
lazy val appContainer = AppContainer(pgContainer.jdbcUrl, pgContainer.username, pgContainer.password)
val containers = …
```
> Removed shapeless and make LazyContainer required for MultipleContainers

- build.sbt
> Update testContainer Version to 1.8.2

- README.md
- build.sbt
- src/test/resources/docker-compose.yml
- src/test/scala/com/dimafeng/testcontainers/integration/ComposeSpec.scala
Figured out that the failing tests in #30 were due to the fact that `elasticsearch:latest` is not available in Docker Hub anymore... so added versions in `docker-compose.yml` to prevent this from happening in the future and moving on :smile: 
On a side note current master is not building as well because of that same issue...
@bskarda @dimafeng
> Upgrade testcontainers version to 1.9.1 and added versions in docker-compose.yml

- build.sbt
- Bumped `testcontainers` to latest `1.10.1`
- Bumped `scalatest` to latest `3.0.5`
> Bumping testcontainers and scalatest versions

- build.sbt
Upgrade to Scala 2.13.0-RC2.
This is necessary to support 2.13.0-RC2 in matsluni/aws-spi-akka-http (see: matsluni/aws-spi-akka-http#8).
> Upgrade to Scala 2.13.0-RC2

- README.md
- src/main/scala/com/dimafeng/testcontainers/DockerComposeContainer.scala
- src/main/scala/com/dimafeng/testcontainers/MultipleContainers.scala
- src/main/scala/com/dimafeng/testcontainers/SeleniumTestContainerSuite.scala
- src/main/scala/com/dimafeng/testcontainers/TestContainer.scala
- src/main/scala/com/dimafeng/testcontainers/lifecycle/TestLifecycleAware.scala
- src/main/scala/org/testcontainers/containers/TestContainerAccessor.scala
- src/test/scala/com/dimafeng/testcontainers/ContainerSpec.scala
- src/test/scala/com/dimafeng/testcontainers/MultipleContainersSpec.scala
- version.sbt
testcontainers-java reworked lifecycle of the containers a bit. This pull request is to support these changes.
* New `TestLifecycleAware` trait introduced. It's a copy of java's interface, but with scala's `Option` type. Users of the library can use it when they want to do something with the container before or after the test. Personally, I'm against this feature at all, but I didn't convince the core java team that this feature is redundant. So, we have to support this. Also, I could just reuse java's interface, but I don't think that it's a good idea. Scala's hierarchy is completely separate from the java's, and it would be very unnatural for the scala users to work with the java's Optional.
* `Container` now implements `Startable` java interface with `start` and `stop` methods.. I …
> Deprecate old lifecycle methods

- modules/cassandra/src/main/scala/com/dimafeng/testcontainers/CassandraContainer.scala
It seems like there is a bug in configuring init scripts on Cassandra container. This PR fixes that bug.
> Fixed a bug with configuring init script on Cassandra container.

- core/src/main/scala/com/dimafeng/testcontainers/DockerComposeContainer.scala
- core/src/main/scala/com/dimafeng/testcontainers/FixedHostPortGenericContainer.scala
- core/src/main/scala/com/dimafeng/testcontainers/GenericContainer.scala
- modules/cassandra/src/main/scala/com/dimafeng/testcontainers/CassandraContainer.scala
- modules/kafka/src/main/scala/com/dimafeng/testcontainers/KafkaContainer.scala
- modules/mysql/src/main/scala/com/dimafeng/testcontainers/MySQLContainer.scala
- modules/postgres/src/main/scala/com/dimafeng/testcontainers/PostgreSQLContainer.scala
- modules/vault/src/main/scala/com/dimafeng/testcontainers/VaultContainer.scala
- test-framework/scalatest-selenium/src/main/scala/com/dimafeng/testcontainers/SeleniumTestContainerSuite.scala
This change is a minor simplification of an inner codebase.
1. We don't need this kind of types and can replace them with just `SomeType[_]` (without `forSome`) because we don't have any specific usage of existential types in the codebase.
2. We can remove them because they are not a part of a public API.
3. In scala 3 existential types [will be dropped](https://dotty.epfl.ch/docs/reference/dropped-features/existential-types.html)
> Removed existential types from containers

- test-framework/scalatest/src/main/scala/com/dimafeng/testcontainers/TestContainers.scala
Fixes #81 
Ran `sbt test` and it doesn't seem there is any regression.
> Define container as `def`, not `val`

- README.md
- core/src/main/scala/com/dimafeng/testcontainers/Container.scala
- core/src/main/scala/com/dimafeng/testcontainers/ContainerDef.scala
- core/src/main/scala/com/dimafeng/testcontainers/DockerComposeContainer.scala
- core/src/main/scala/com/dimafeng/testcontainers/FixedHostPortGenericContainer.scala
- core/src/main/scala/com/dimafeng/testcontainers/GenericContainer.scala
- core/src/main/scala/com/dimafeng/testcontainers/lifecycle/Stoppable.scala
- core/src/test/scala/com/dimafeng/testcontainers/BaseSpec.scala
- core/src/test/scala/com/dimafeng/testcontainers/lifecycle/AndableTest.scala
- modules/cassandra/src/main/scala/com/dimafeng/testcontainers/CassandraContainer.scala
- modules/kafka/src/main/scala/com/dimafeng/testcontainers/KafkaContainer.scala
- modules/mysql/src/main/scala/com/dimafeng/testcontainers/MySQLContainer.scala
- modules/postgres/src/main/scala/com/dimafeng/testcontainers/PostgreSQLContainer.scala
- modules/vault/src/main/scala/com/dimafeng/testcontainers/VaultContainer.scala
- test-framework/scalatest-selenium/src/test/scala/com/dimafeng/testcontainers/integration/SeleniumSpec.scala
- test-framework/scalatest/src/main/scala/com/dimafeng/testcontainers/scalatest/TestContainerForAll.scala
- test-framework/scalatest/src/main/scala/com/dimafeng/testcontainers/scalatest/TestContainerForEach.scala
- test-framework/scalatest/src/main/scala/com/dimafeng/testcontainers/scalatest/TestContainersForAll.scala
- test-framework/scalatest/src/main/scala/com/dimafeng/testcontainers/scalatest/TestContainersForEach.scala
- test-framework/scalatest/src/main/scala/com/dimafeng/testcontainers/scalatest/TestContainersSuite.scala
- test-framework/scalatest/src/test/scala/com/dimafeng/testcontainers/ContainerSpec.scala
- test-framework/scalatest/src/test/scala/com/dimafeng/testcontainers/MultipleContainersSpec.scala
- test-framework/scalatest/src/test/scala/com/dimafeng/testcontainers/SampleContainer.scala
- test-framework/scalatest/src/test/scala/com/dimafeng/testcontainers/integration/GenericContainerDefSpec.scala
- test-framework/scalatest/src/test/scala/com/dimafeng/testcontainers/scalatest/TestContainerForAllSpec.scala
- test-framework/scalatest/src/test/scala/com/dimafeng/testcontainers/scalatest/TestContainerForEachSpec.scala
- test-framework/scalatest/src/test/scala/com/dimafeng/testcontainers/scalatest/TestContainersForAllSpec.scala
- test-framework/scalatest/src/test/scala/com/dimafeng/testcontainers/scalatest/TestContainersForEachSpec.scala
- version.sbt
This pull request is based on these experiments: https://github.com/testcontainers/testcontainers-scala/pull/54
All changes in this pull request are backward compatible. Old tests and containers will continue to work without changes.
The main motivation was the problem with the mutable nature of the `Container`. I and many users of testcontainers-scala are facing the problem with this. A typical example: trying to get a mapped port from the unstarted container. The current API allows doing this.
Another problem is `lazy` stuff in the current API. There is no way to _force_ user to use `lazy`.
So, I'm trying to create more typesafe API for the scala facade. Here are the main implementation points:
1. `ContainerDef` — it's container definition. Its goal is to start a specific docker …
> New API and DSL

- build.sbt
Microfix for publishing `allOld` project. I managed to use `sbt release` with `+publishLocal` instead of `+publishSinged` all it seems it works fine.
> Fixing aggregated module deploy

- build.sbt
- project/Dependencies.scala
To maintain `allOld` package fully backward compatible we need to:
1. Exclude compile transitive dependencies from `com.dimafeng:*` modules.
2. Re-add this compile transitive dependencies with the `provided` configuration.
With this, we will produce `pom.xml` with the same effects as the old `pom.xml` file.
To achieve this I had to use some sbt black magic. 
What actually done here:
* I moved all dependencies declarations to the `Dependencies` file. I need it to reuse dependencies from .different projects. And overall it is a good practice to do this because it makes your `build.sbt` file less noisy.
* I removed all extra modifiers in `dependsOn` block in `allOld` project. It gives nothing in my case.
* I added a `pomPostProcess` step. That's where the fun begins. I actually rewrite some …
> Fixing pom.xml for allOld package

- README.md
- test-framework/scalatest/src/main/scala/com/dimafeng/testcontainers/scalatest/TestContainersForAll.scala
- test-framework/scalatest/src/main/scala/com/dimafeng/testcontainers/scalatest/TestContainersForEach.scala
- test-framework/scalatest/src/main/scala/com/dimafeng/testcontainers/scalatest/TestContainersSuite.scala
- test-framework/scalatest/src/test/scala/com/dimafeng/testcontainers/scalatest/TestContainerForAllSpec.scala
- test-framework/scalatest/src/test/scala/com/dimafeng/testcontainers/scalatest/TestContainerForEachSpec.scala
- test-framework/scalatest/src/test/scala/com/dimafeng/testcontainers/scalatest/TestContainersForAllSpec.scala
- test-framework/scalatest/src/test/scala/com/dimafeng/testcontainers/scalatest/TestContainersForEachSpec.scala
I tried to use a new API in the real codebase and faced a few problems. With this pull request I fixed them.
* Changed signature of `def withContainers(runTest: Containers => Unit): Unit` to `def withContainers[A](runTest: Containers => A): A`. This improvement makes `withContainers` function usable in `Async*` specs and in user-defined utility wrappers around `withContainers`.
* Also, I tried to use `afterStart` and `beforeStop` method and realized, that they are useless without containers inside. So, I added `containers: Containers` argument to both these methods. Also, I renamed them to `afterContainersStart` and `beforeContainersStop`, because these names are a lot more suitable for these methods after my changes.
I think these fixes should be released with 0.34.1 version. API was …
> Improvements in the new api

- README.md
- modules/oracle/src/main/scala/com/dimafeng/testcontainers/OracleContainer.scala
- modules/oracle/src/test/scala/com/dimafeng/testcontainers/OracleSpec.scala
Removed `dockerImageName` from the `OracleContainer`, because oracle doesn't provide any official image. More details here: https://testcontainers.slack.com/archives/C9EJ7TVT7/p1576740487005000
Also, I added changelog for 0.34.2.
> Remove dockerImageName for OracleContainer

- README.md
- core/src/main/scala/com/dimafeng/testcontainers/DockerComposeContainer.scala
> Added DockerComposeContainer.Def

- README.md
- build.sbt
- core/src/main/scala/com/dimafeng/testcontainers/Container.scala
- core/src/main/scala/com/dimafeng/testcontainers/GenericContainer.scala
- modules/cassandra/src/main/scala/com/dimafeng/testcontainers/CassandraContainer.scala
- modules/clickhouse/src/main/scala/com/dimafeng/testcontainers/ClickHouseContainer.scala
- modules/cockroachdb/src/main/scala/com/dimafeng/testcontainers/CockroachContainer.scala
- modules/couchbase/src/main/scala/com/dimafeng/testcontainers/CouchbaseContainer.scala
- modules/db2/src/main/scala/com/dimafeng/testcontainers/Db2Container.scala
- modules/dynalite/src/main/scala/com/dimafeng/testcontainers/DynaliteContainer.scala
- modules/elasticsearch/src/main/scala/com/dimafeng/testcontainers/ElasticsearchContainer.scala
- modules/influxdb/src/main/scala/com/dimafeng/testcontainers/InfluxDBContainer.scala
- modules/jdbc/src/main/scala/com/dimafeng/testcontainers/JdbcDatabaseContainer.scala
- modules/localstack/src/main/scala/com/dimafeng/testcontainers/LocalStackContainer.scala
- modules/mariadb/src/main/scala/com/dimafeng/testcontainers/MariaDBContainer.scala
- modules/mockserver/src/main/scala/com/dimafeng/testcontainers/MockServerContainer.scala
- modules/mssqlserver/src/main/scala/com/dimafeng/testcontainers/MSSQLServerContainer.scala
- modules/mysql/src/main/scala/com/dimafeng/testcontainers/MySQLContainer.scala
- modules/nginx/src/main/scala/com/dimafeng/testcontainers/NginxContainer.scala
- modules/postgres/src/main/scala/com/dimafeng/testcontainers/PostgreSQLContainer.scala
- modules/pulsar/src/main/scala/com/dimafeng/testcontainers/PulsarContainer.scala
- modules/rabbitmq/src/main/scala/com/dimafeng/testcontainers/RabbitMQContainer.scala
- modules/toxiproxy/src/main/scala/com/dimafeng/testcontainers/ToxiproxyContainer.scala
- modules/vault/src/main/scala/com/dimafeng/testcontainers/VaultContainer.scala
- project/Dependencies.scala
- version.sbt
Fix for #95, #80
Most of the changes here are pretty mechanical. But some containers were pretty complex.
I didn't add tests. This is not good in general, but most of the containers are so simple and straightforward so I think it could be done in the future when some issues will be found. 
A detailed review of changes you can find in the changelog section of the readme.
> Parity with testcontainers-java

- README.md
- modules/clickhouse/src/main/scala/com/dimafeng/testcontainers/ClickHouseContainer.scala
- modules/clickhouse/src/test/scala/com/dimafeng/testcontainers/ClickHouseContainerSpec.scala
- project/Dependencies.scala
Fix for #111 
Looks like `dbPassword` parameter was added accidentally. Java container doesn't support it.
> Fix ClickHouseContainer: remove password parameter

- README.md
- build.sbt
- core/src/main/scala/com/dimafeng/testcontainers/DockerComposeContainer.scala
- modules/mysql/src/test/scala/com/dimafeng/testcontainers/MysqlSpec.scala
- modules/orientdb/src/main/scala/com/dimafeng/testcontainers/OrientDBContainer.scala
- modules/presto/src/main/scala/com/dimafeng/testcontainers/PrestoContainer.scala
- project/Dependencies.scala
- version.sbt
* testcontainers-java updated to 1.13.0.
* Added `OrientDBContainer`.
* Added `PrestoContainer`.
* Added `DockerComposeContainer.getContainerByServiceName method`.
* Change module dependencies for container modules. They now depend on the core module and not depend on the scalatest module.
* Up version to the 0.36.0.
> Updating testcontainers-java to 1.13.0

- modules/rabbitmq/src/main/scala/com/dimafeng/testcontainers/RabbitMQContainer.scala
Passing through image name to java container constructor
> Image name bug fix

- README.md
- modules/influxdb/src/main/scala/com/dimafeng/testcontainers/InfluxDBContainer.scala
- modules/mariadb/src/main/scala/com/dimafeng/testcontainers/MariaDBContainer.scala
- modules/mssqlserver/src/main/scala/com/dimafeng/testcontainers/MSSQLServerContainer.scala
- modules/mysql/src/main/scala/com/dimafeng/testcontainers/MySQLContainer.scala
- modules/nginx/src/main/scala/com/dimafeng/testcontainers/NginxContainer.scala
- modules/postgres/src/main/scala/com/dimafeng/testcontainers/PostgreSQLContainer.scala
- modules/presto/src/main/scala/com/dimafeng/testcontainers/PrestoContainer.scala
- modules/vault/src/main/scala/com/dimafeng/testcontainers/VaultContainer.scala
Fix for #127
Scala compiler infers types of containers with `SELF` type parameter to `Foo[Nothing]` instead of `Foo[_]` and it leads to a class cast exception. I added explicit signatures and the issue is gone. Also, I fixed this issue in all other containers with `SELF` type parameter in the signature.
These issues could have been avoided if we had tests for at least a happy path for all containers.
> Fix 0.38.0 regression

- build.sbt
- modules/mongodb/src/main/scala/com/dimafeng/testcontainers/MongoDBContainer.scala
- modules/mongodb/src/test/scala/com/dimafeng/testcontainers/integration/MongoSpec.scala
Hi, in this PR i fixed an issue when creating a `MongoDBContainer` without a specific tag.  It was crashing because the default tag was `4.0.10` instead of `mongo:4.0.10`, this was causing an exception downloading the (wrong) container image.
I fixed it removing the default tag in the `MongoDBContainer` class and delegating it to the underlying java container.
In addition i refactored the class to be more in line with the other modules and added some tests.
> fix default image-tag name in MongoDBContainer 

- modules/solr/src/main/scala/com/dimafeng/testcontainers/SolrContainer.scala
Some of `SolrContainer`'s properties can be omitted but in the current implementation, `null` is given for some properties if we don't specify and it causes `IllegalArgumentException` in the Java implementation of `SolrContainer`.
For example:
https://github.com/testcontainers/testcontainers-java/blob/53932d9988e8e09db45c8ccea0f39d0da7a24dc5/modules/solr/src/main/java/org/testcontainers/containers/SolrContainer.java#L59-L61
It would be better to skip to set if they are not specified explicitly.
> Don't set SolrContainer properties if not specified to avoid IllegalArgumentException

- build.sbt
- modules/localstackV2/src/main/scala/com/dimafeng/testcontainers/LocalStackV2Container.scala
- project/Dependencies.scala
Addresses #135 by adding a separate module for using amazon's v2 java sdk with localstack containers. 
Usage example: 
```
S3Client.builder()
.endpointOverride(container.endpointOverride(Service.S3))
.credentialsProvider(container.staticCredentialsProvider)
.region(container.region)
.build()
```
Compared to the usage example for the underlying container with the v2 sdk https://www.testcontainers.org/modules/localstack/
> add localstack container for using amazon java sdk v2

- README.md
Overriding container with a `def` seems to be a common mistake since IntelliJ overrides with a `def` by default (I actually did it, see https://github.com/testcontainers/testcontainers-scala/issues/137). Hope this note will lead to less people experiencing it while not growing too much the "Quick Start" section.
> Added a note about overriding container property

- README.md
Adds an example of defining and starting a container, from a docker-compose file, using the new API (#78, support added #100).
I had to search around a bit to find out how to use the new API, so I thought adding an example might help others.
If you'd rather avoid over-complicating the Readme examples I'm happy to close the PR. Whatever works 👍
> Document DockerComposeContainer usage

- project/Dependencies.scala
Junit 4.13 is vulnerable to information exposure, which got fixed in 4.13.1:
https://app.snyk.io/vuln/SNYK-JAVA-JUNIT-1017047
It's a low severity vulnerability, but the fix is easy.
> Update JUnit dependency to 4.13.1

- modules/localstack/src/main/scala/com/dimafeng/testcontainers/LocalStackContainer.scala
I found I had to bump the `localstack` version to successfully send SQS messages using the AWS JDK 2 with fifo queues.
> Update localstack to 12.12 from 0.9.4

- build.sbt
[Scaladex](https://index.scala-lang.org/)'s data about [`testcontainers-scala`](https://index.scala-lang.org/testcontainers/testcontainers-scala/testcontainers-scala) is extremely incomplete - [only a few old artifacts show up](https://user-images.githubusercontent.com/52038/133003938-aa30b39c-f873-4087-b5b7-2750a7644ace.png)... this is because, back in March 2018 with e983e479, there was a small typo where instead of `GitHubHosting` being specified (which would have been correct), the alternate `GitLabHosting` host was specified in `testcontainers-scala` Sonatype configuration in sbt.
Scaladex is very particular about matching up GitHub repos with their Sonatype metadata (see eg https://github.com/scalacenter/scaladex/issues/657#issuecomment-803899871 ) so this error unfortunately means …
> Fix Scaladex listing by updating Sonatype info to correct git host

- README.md
- core/src/main/scala/com/dimafeng/testcontainers/GenericContainer.scala
- test-framework/scalatest/src/test/scala/com/dimafeng/testcontainers/GenericContainerSpec.scala
Just adds an alias for creating a `ContainerDef` for a `GenericContainer` that doesn't involve creating a new object/class.
Example:
```scala
import scala.io.Source
import java.net.URL
import org.scalatest.flatspec.AnyFlatSpec
import com.dimafeng.testcontainers.GenericContainer
import com.dimafeng.testcontainers.scalatest.TestContainerForAll
import org.testcontainers.containers.wait.strategy.Wait
class GenericContainerSpec extends AnyFlatSpec with TestContainerForAll {
override val containerDef = GenericContainer.Def.anonymous("nginx:latest",
exposedPorts = Seq(80),
waitStrategy = Wait.forHttp("/")
)
"GenericContainer" should "start nginx and expose 80 port" in withContainers { container =>
assert(Source.fromInputStream(
new URL(s"http://${container.containerIpAddress}::${container.mappedP …
```
> Add alias for creating a generic container definition

- core/src/main/scala/com/dimafeng/testcontainers/GenericContainer.scala
Closes https://github.com/testcontainers/testcontainers-scala/issues/197
> Fix:  Image pull policy not applied in GenericContainer

- core/src/main/scala/com/dimafeng/testcontainers/FixedHostPortGenericContainer.scala
- core/src/main/scala/com/dimafeng/testcontainers/GenericContainer.scala
> Add `withFileSystemBind` + name parameters

- modules/kafka/src/main/scala/com/dimafeng/testcontainers/KafkaContainer.scala
- modules/kafka/src/test/scala/com/dimafeng/testcontainers/integration/SchemaRegistrySpec.scala
Hi, here is my proposal to change deprecated `JavaKafkaContainer` class with String argument to newer class with `DockerImageName` argument. (like in ElasticSearch module)
> chore: rid of deprecated class

- core/src/main/scala/com/dimafeng/testcontainers/FixedHostPortGenericContainer.scala
- core/src/main/scala/com/dimafeng/testcontainers/GenericContainer.scala
The PR adds `startupCheckStrategy`  to the DSL for `FixedHostPortGenericContainer` and `GenericContainer`.
> Add startupCheckStrategy

- modules/localstackV2/src/main/scala/com/dimafeng/testcontainers/LocalStackV2Container.scala
- project/Dependencies.scala
Hey there! 👋 
For reasons similar @jbwheatley's previous localstack PRs/issues:
https://github.com/testcontainers/testcontainers-scala/issues/135
https://github.com/testcontainers/testcontainers-scala/pull/136
... I need to introduce the sqs dependency for the localstack to avoid the dreaded 
```
A needed class was not found. This could be due to an error in your runpath. Missing class: com/amazonaws/auth/AWSCredentials
java.lang.NoClassDefFoundError: com/amazonaws/auth/AWSCredentials
```
I hope it's ok that as part of this I've also bumped the aws library version + the default tag for the V2 stack to bring it in line with V1 as per https://github.com/testcontainers/testcontainers-scala/pull/183
> Localstack (+V2) dependencies

- .github/workflows/test.yml
- modules/gcloud/src/test/scala/com/dimafeng/testcontainers/FirestoreEmulatorContainerSpec.scala
- project/Dependencies.scala
Ensuring (via CI/CD) that tests run in Java env 8, 11 and 17.
**Note 1:** Fixed error with Java 8
```
[error] .../testcontainers-scala/modules/gcloud/src/test/scala/com/dimafeng/testcontainers/FirestoreEmulatorContainerSpec.scala:19:25: value of is not a member of object java.util.Map
[error]         val data = JMap.of("first", "Ada", "last", "Lovelace")
```
**Note 2: ** Fixed error with Java 17
```
[info] com.dimafeng.testcontainers.integration.VaultSpec *** ABORTED ***
[info]   java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.reflection.ReflectionCache
[info]   at org.codehaus.groovy.runtime.dgmimpl.NumberNumberMetaMethod.<clinit>(NumberNumberMetaMethod.java:33)
[info]   ...
[info]   Cause: java.lang.ExceptionInInitializerError: Exception …
```
> Add Java 17 support

- README.md
- build.sbt
- docs/src/main/tut/index.md
I noticed the badge was pointing to an out-of-date CI, now reflecting GitHub actions pipeline.
> Fix CI badge

- modules/oracle/src/main/scala/com/dimafeng/testcontainers/OracleContainer.scala
OracleContainer is the only RDBMS container that doesn't implement JdbcDatabaseContainer. It makes it hard to work with these containers in a more abstract way.
> Make OracleContainer extend JdbcDatabaseContainer

- modules/mockserver/src/main/scala/com/dimafeng/testcontainers/MockServerContainer.scala
Solves https://github.com/testcontainers/testcontainers-scala/issues/213
Current MockServerContainer uses deprecated constructors from testcontainers-java. This PR introduces constructing image name using DockerImageName utility without changing the API of MockServerContainer.
Unfortunately there's no way to use the defaults from testcontainers-java because they're declared as private, so in this PR I'm introducing the latest image from `mockserver/mockserver` repo (as opposed to the deprecated `jamesdbloom/mockserver` used by testcontainers-java).
> Fix MockServer container tag

- modules/gcloud/src/main/scala/com/dimafeng/testcontainers/BigtableEmulatorContainer.scala
- modules/gcloud/src/main/scala/com/dimafeng/testcontainers/FirestoreEmulatorContainer.scala
- modules/gcloud/src/main/scala/com/dimafeng/testcontainers/PubSubEmulatorContainer.scala
These are needed if using testcontainers-scala with munit.
> ContainerDef constructors for gcloud containers

- modules/kafka/src/main/scala/com/dimafeng/testcontainers/KafkaContainer.scala
Confluent now provides official arm64-based images. Supersedes #223
> Update Kafka version, remove ARM-specific image name

- project/Dependencies.scala
I get three test failures locally:
```
[error] (moduleOracle / Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] (scalatestSelenium / Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] (moduleNeo4j / Test / test) sbt.TestsFailedException: Tests unsuccessful
```
I was hoping CI would run on PRs here - locally they may be because of running on Apple Silicon
> rev testcontainers to 1.17.5

- modules/rabbitmq/src/main/scala/com/dimafeng/testcontainers/RabbitMQContainer.scala
- modules/rabbitmq/src/test/scala/com/dimafeng/testcontainers/RabbitMQSpec.scala
It was not possible to properly configure `RabbitMQContainer` when using it with `munit` due to the missing parameters in `RabbitMQContainer.Def`. I added them, along with a simple test to see if everything works properly.
> bugfix: It is now possible to pass params into RabbitMQ Def

- core/src/main/scala/com/dimafeng/testcontainers/Container.scala
- project/Dependencies.scala
https://github.com/testcontainers/testcontainers-java/releases/tag/1.19.0
> Bump testcontianers-java 1.19.0

- core/src/main/scala/com/dimafeng/testcontainers/DockerComposeContainer.scala
- test-framework/scalatest/src/test/scala/com/dimafeng/testcontainers/integration/ComposeWaitingForSpec.scala
This PR requires #259 to get merged first.
Close #200
This PR aims to migrate to the backend of `com.dimafeng.testcontainers.DockerComposeContainer` from Docker Compose V1 (a.k.a `docker-compose`) to the Docker Compose V2 (a.k.a `docker compose`)
See more details at https://github.com/testcontainers/testcontainers-java/pull/5608
> From July 2023 Compose V1 stopped receiving updates. It’s also no longer available in new releases of Docker Desktop.
https://docs.docker.com/compose/migrate/
Compose V1 actually reached EOL, and Compose V2 has been adopted for a long time, so I suppose the change won't break user experience.
Before this PR, `docker-compose` is necessary for launching compose files.
After this PR, all tests passed without `docker-compose` but only `docker` commands
> Migrate to Docker Compose v2

- build.sbt
- docs/src/main/tut/setup.md
- modules/minio/src/main/scala/com/dimafeng/testcontainers/MinIOContainer.scala
- project/Dependencies.scala
This adds in MinIO as a test container and bumps the testcontainer version to 1.19.1
> Bumps testcontainers-java to 1.19.1 and adds in MinIO

- core/src/main/scala/com/dimafeng/testcontainers/Container.scala
- core/src/main/scala/com/dimafeng/testcontainers/DockerComposeContainer.scala
- core/src/main/scala/com/dimafeng/testcontainers/MultipleContainers.scala
- core/src/main/scala/com/dimafeng/testcontainers/implicits/DockerImageNameConverters.scala
- core/src/main/scala/org/testcontainers/containers/TestContainerAccessor.scala
- modules/vault/src/main/scala/com/dimafeng/testcontainers/VaultContainer.scala
- project/build.properties
- bump sbt version to 1.9.8
- fix `@`deprecated annotations, it should accept two arguments
```scala
[warn] /Users/roman/git/github.com/testcontainers-scala/core/src/main/scala/org/testcontainers/containers/TestContainerAccessor.scala:5:2: @deprecated now takes two arguments; see the scaladoc.
[warn] @deprecated("Should be replaced by lifecycle methods")
[warn]  ^
[warn] /Users/roman/git/github.com/testcontainers-scala/core/src/main/scala/com/dimafeng/testcontainers/MultipleContainers.scala:11:4: @deprecated now takes two arguments; see the scaladoc.
[warn]   @deprecated("Use `stop` instead")
[warn]    ^
[warn] /Users/roman/git/github.com/testcontainers-scala/core/src/main/scala/com/dimafeng/testcontainers/MultipleContainers.scala:14:4: @deprecated now takes two arguments; see the …
```
> fix deprecated annotations, bump sbt version

- build.sbt
- modules/localstackV2/src/main/scala/com/dimafeng/testcontainers/LocalStackV2Container.scala
- modules/localstackV2/src/test/scala/com/dimafeng/testcontainers/LocalStackV2Spec.scala
- project/Dependencies.scala
- fixed deprecation warning
```scala
[warn] testcontainers-scala/modules/localstackV2/src/main/scala/com/dimafeng/testcontainers/LocalStackV2Container.scala:14:13: constructor LocalStackContainer in class LocalStackContainer is deprecated: see corresponding Javadoc for more information.
[warn]     val c = new JavaLocalStackContainer(tag)
[warn]             ^
[warn] one warning found
```
- added basic unit test for LocalStackV2 container
- changed a bit arguments signature in helper methods for dependencies
- bump aws-toolkit v2 version
> minor updates for LocalStackV2Container

- .github/workflows/test.yml
This will fix the "no space left" error on GitHub Actions runners encountered in #273 and #272:
```
System.IO.IOException: No space left on device: '/home/runner/runners/2.312.0/_diag/Worker_20240210-081954-utc.log'
```
The fix is inspired by the CI configuration in [testcontainers-dotnet](https://github.com/testcontainers/testcontainers-dotnet/blob/develop/.github/workflows/cicd.yml#L48-L64).
The CI configuration was tested in the [forked repository](https://github.com/greshny-forks/testcontainers-scala/pull/2), where CI runs took 2-3 minutes longer.
Result output is:
```
/dev/root:
********************************************************************************
=> Saved 32GiB
********************************************************************************
overall: …
```
> add "Free space" step

- build.sbt
- modules/mockserver/src/main/scala/com/dimafeng/testcontainers/MockServerContainer.scala
- modules/mockserver/src/test/scala/com/dimafeng/testcontainers/MockServerSpec.scala
- project/Dependencies.scala
- add unit test for testcontainers-scala-mockserver 
- Add a `serverHost` method to the MockServerContainer for easier usage with MockServerClient
> Add unit tests and `serverHost` to MockServerContainer

- build.sbt
- docs/src/main/tut/setup.md
- modules/wiremock/src/main/scala/com/dimafeng/testcontainers/WireMockContainer.scala
- modules/wiremock/src/test/resources/bar_body.json
- modules/wiremock/src/test/resources/bar_mapping.json
- modules/wiremock/src/test/resources/foo_mapping.json
- modules/wiremock/src/test/scala/com/dimafeng/testcontainers/WireMockSpec.scala
- project/Dependencies.scala
Hello, thanks a lot for your work on the lib!
This PR adds a wrapper for Java `WireMockContainer` with functionallity needed for our use-case. I'm not 100% sure about the approach for calling builder methods on the underlying container. If you think it's an OK approach, I will also add support for the rest of the builder methods and some documentation.
> Add WireMock container wrapper

- modules/postgres/src/main/scala/com/dimafeng/testcontainers/PostgreSQLContainer.scala
fixes:
```scala
[info] compiling 1 Scala source to /Users/roman/git/github.com/testcontainers-scala/modules/postgres/target/scala-3.1.2/classes ...
[warn] -- Deprecation Warning: /Users/roman/git/github.com/testcontainers-scala/modules/postgres/src/main/scala/com/dimafeng/testcontainers/PostgreSQLContainer.scala:21:12 
[warn] 21 |        new JavaPostgreSQLContainer()
[warn]    |            ^^^^^^^^^^^^^^^^^^^^^^^
[warn]    |constructor PostgreSQLContainer in class PostgreSQLContainer is deprecated since : see corresponding Javadoc for more information.
[warn] one warning found
```
> fix deprecation warning for PostgreSQLContainer

- docs/src/main/tut/usage.md
There was a nginx container reference called 'mySqlContainer' on an example in usage.md
> fix: typo on usage.md

- core/src/main/scala/com/dimafeng/testcontainers/FixedHostPortGenericContainer.scala
- test-framework/scalatest/src/test/scala/com/dimafeng/testcontainers/integration/FixedHostPortContainerSpec.scala
* add Def pattern for FixedHostPortGenericContainer
* make fixed port declaration via Seq. This allows containers with more than one port to be raised. For example https://github.com/Grokzen/docker-redis-cluster
This is done because there are difficulties with colima on mac os and testcontainers and there is a need to run the redis-cluster container on all fixed ports
Welcome to suggestions
> Add Def pattern for FixedHostPortGenericContainer and seq port bindings

- build.sbt
- modules/yugabytedb/src/main/scala/com/dimafeng/testcontainers/YugabyteDBYCQLContainer.scala
- modules/yugabytedb/src/main/scala/com/dimafeng/testcontainers/YugabyteDBYSQLContainer.scala
- modules/yugabytedb/src/test/resources/init_yql.sql
- modules/yugabytedb/src/test/scala/com/dimafeng/testcontainers/YugabyteDBCQLSpec.scala
- modules/yugabytedb/src/test/scala/com/dimafeng/testcontainers/YugabyteDBSQLSpec.scala
- project/Dependencies.scala
Wrappers for YugabyteDBYCQLContainer and YugabyteDBYSQLContainer
> Add wrappers for YugabyteDB

- modules/milvus/src/main/scala/com/dimafeng/testcontainers/MilvusContainer.scala
Remove exposing ports, since this is done in the underlying container.
> Remove redundant params in MilvusContainer

- core/src/main/scala/com/dimafeng/testcontainers/Container.scala
- core/src/main/scala/com/dimafeng/testcontainers/FixedHostPortGenericContainer.scala
- core/src/main/scala/com/dimafeng/testcontainers/GenericContainer.scala
- core/src/main/scala/com/dimafeng/testcontainers/MultipleContainers.scala
- modules/cassandra/src/main/scala/com/dimafeng/testcontainers/CassandraContainer.scala
- modules/influxdb/src/main/scala/com/dimafeng/testcontainers/InfluxDBContainer.scala
- modules/jdbc/src/main/scala/com/dimafeng/testcontainers/JdbcDatabaseContainer.scala
- modules/mariadb/src/main/scala/com/dimafeng/testcontainers/MariaDBContainer.scala
- modules/mssqlserver/src/main/scala/com/dimafeng/testcontainers/MSSQLServerContainer.scala
- modules/mysql/src/main/scala/com/dimafeng/testcontainers/MySQLContainer.scala
- modules/neo4j/src/main/scala/com/dimafeng/testcontainers/Neo4jContainer.scala
- modules/nginx/src/main/scala/com/dimafeng/testcontainers/NginxContainer.scala
- modules/postgres/src/main/scala/com/dimafeng/testcontainers/PostgreSQLContainer.scala
- modules/presto/src/main/scala/com/dimafeng/testcontainers/PrestoContainer.scala
- modules/toxiproxy/src/main/scala/com/dimafeng/testcontainers/ToxiproxyContainer.scala
- modules/vault/src/main/scala/com/dimafeng/testcontainers/VaultContainer.scala
- test-framework/munit/src/test/scala/com/dimafeng/testcontainers/munit/fixtures/ForAllTestContainersFixtureSpec.scala
- test-framework/munit/src/test/scala/com/dimafeng/testcontainers/munit/fixtures/ForEachTestContainersFixtureSpec.scala
- test-framework/scalatest-selenium/src/main/scala/com/dimafeng/testcontainers/SeleniumTestContainerSuite.scala
- test-framework/scalatest/src/test/scala/com/dimafeng/testcontainers/integration/GenericContainerDefSpec.scala
old wildcard syntax `[_]` is deprecated in latest Scala 3.
```
Welcome to Scala 3.6.3 (21.0.5, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
scala> val a: List[_] = Nil
1 warning found
-- Warning: --------------------------------------------------------------------
1 |val a: List[_] = Nil
|            ^
|        `_` is deprecated for wildcard arguments of types: use `?` instead
val a: List[?] = List()
scala> val b: List[?] = Nil
val b: List[?] = List()
```
> replace to new wildcard syntax

- modules/localstack/src/main/scala/com/dimafeng/testcontainers/LocalStackContainer.scala
- modules/localstackV2/src/main/scala/com/dimafeng/testcontainers/LocalStackV2Container.scala
Hi, excellent repo!
This updates localstack to the latest version on dockerhub.
The trigger for this was so I can use the newer localstack docker images built for arm64.
> Update localstack to 4.0.3

- .github/workflows/ci-release.yml
- .github/workflows/test.yml
- project/build.properties
- sbt
The bundled `sbt` script is outdated, for example, it can not process java_version correctly.
```
$ ./sbt compile
./sbt: line 204: [[: .: syntax error: operand expected (error token is ".")
Unrecognized VM option 'MaxPermSize=384m'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
This PR Bump SBT 1.10.7 and sync the `sbt` script from https://github.com/sbt/sbt/blob/v1.10.7/sbt
> Bump SBT 1.10.7 and update sbt script

- modules/clickhouse/src/main/scala/com/dimafeng/testcontainers/ClickHouseContainer.scala
The ClickHouseContainer stopped working recently due to the `default` user is not allowed to access from outside of the container without setting CLICKHOUSE_PASSWORD. See details at https://github.com/testcontainers/testcontainers-java/pull/9942
```
/entrypoint.sh: neither CLICKHOUSE_USER nor CLICKHOUSE_PASSWORD is set, disabling network access for user 'default'
```
Unfortunately, the Scala-wrapped ClickHouseContainer does not expose those args so nothing I can do to workaround the test failure in downstream projects.
Changes are verified locally by 
```
$ sbt moduleClickhouse/test
... 
[info] ClickHouseContainer
[info] - should work
[info] Run completed in 5 seconds, 563 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 1, …
```
> Expose database, username, password args for ClickHouseContainer

- build.sbt
- modules/gcloud/src/test/scala/com/dimafeng/testcontainers/FirestoreEmulatorContainerSpec.scala
- project/Dependencies.scala
- test-framework/specs2/src/main/scala/com/dimafeng/testcontainers/specs2/TestContainerForAll.scala
- test-framework/specs2/src/main/scala/com/dimafeng/testcontainers/specs2/TestContainerForEach.scala
- test-framework/specs2/src/main/scala/com/dimafeng/testcontainers/specs2/TestContainersForAll.scala
- test-framework/specs2/src/main/scala/com/dimafeng/testcontainers/specs2/TestContainersForEach.scala
- test-framework/specs2/src/main/scala/com/dimafeng/testcontainers/specs2/TestContainersSuite.scala
- test-framework/specs2/src/test/scala/com/dimafeng/testcontainers/specs2/SampleContainer.scala
- test-framework/specs2/src/test/scala/com/dimafeng/testcontainers/specs2/TestContainerForAllSpec.scala
- test-framework/specs2/src/test/scala/com/dimafeng/testcontainers/specs2/TestContainerForEachSpec.scala
- test-framework/specs2/src/test/scala/com/dimafeng/testcontainers/specs2/TestContainersForAllSpec.scala
- test-framework/specs2/src/test/scala/com/dimafeng/testcontainers/specs2/TestContainersForEachSpec.scala
> specs2 integration
