testcontainers/testcontainers-scala

gradle.properties, publish.sh, src/main/scala/com/dimafeng/testcontainers/TestContainer.scala
Upgraded to testcontainers 1.4.2 and scala 2.12.3.
=> Testcontainers 1.4.2 and Scala 2.12.3

src/main/scala/com/dimafeng/testcontainers/TestContainer.scala, src/test/scala/com/dimafeng/testcontainers/ContainerSpec.scala
Stop container if some exceptions thrown from **afterStart()** in **ForAllTestContainer**.
=> Stop container if afterStart() failed in ForAllTestContainer

README.md, src/main/scala/com/dimafeng/testcontainers/MySQLContainer.scala, version.sbt
Hi,
I just added some optional parameters to the MysqlContainer constructor to make possible some more fine customization about the db name, the user and the docker image version to use.
Just needed this in a project I'm working on.
=> Mysql container parameters

src/main/scala/com/dimafeng/testcontainers/GenericContainer.scala, src/main/scala/com/dimafeng/testcontainers/TestContainer.scala
Following issue #24, I create this PR which solve the issue and add all the withXXX methods from the Java API.
=> feat(add available Java API methods in DockerComposeContainer scala API)

build.sbt, src/main/scala/com/dimafeng/testcontainers/TestContainer.scala
This PR adds support for Scala 2.13.0-M5.
=> Add support for Scala 2.13.0-M5

build.sbt
This PR bump testcontainers version to 1.11.1.
=> bump testcontainers version to 1.11.1

.travis.yml, build.sbt
=> Support Scala 2.13

build.sbt
Bump testcontainers version to 1.11.3
=> Bump testcontainer version to 1.11.3

build.sbt, src/main/scala/com/dimafeng/testcontainers/VaultContainer.scala, src/test/scala/com/dimafeng/testcontainers/integration/VaultSpec.scala
Adds a VaultContainer wrapper to join the other wrappers.
=> VaultContainer wrapper for o.t.c.VaultContainer and spec

README.md
Added documentation for the modules.
=> Modules docs

build.sbt, modules/oracle/src/main/scala/com/dimafeng/testcontainers/OracleContainer.scala, modules/oracle/src/test/scala/com/dimafeng/testcontainers/OracleSpec.scala, project/Dependencies.scala
Hi!
This should address #43 
I had to create it at work so I thought it would be fair to put it back where it belongs!
Thanks for all the containers! Really helpful
=> #43 Add Oracle Test Container

build.sbt, modules/neo4j/src/main/scala/com/dimafeng/testcontainers/Neo4jContainer.scala, modules/neo4j/src/test/scala/com/dimafeng/testcontainers/Neo4jSpec.scala, project/Dependencies.scala
Added scala impl. of Neo4j DB from java.
=> Neo4j init 

modules/mariadb/src/main/scala/com/dimafeng/testcontainers/MariaDBContainer.scala
Fixes https://github.com/testcontainers/testcontainers-scala/issues/105
=> MariaDB NPE fix

core/src/main/scala/com/dimafeng/testcontainers/DockerComposeContainer.scala, test-framework/scalatest/src/test/scala/com/dimafeng/testcontainers/integration/ComposeWaitingForSpec.scala
Hi there!
I've added `.waitingFor(...)` to Scala wrapper - https://www.testcontainers.org/modules/docker_compose/#local-compose-mode
It could be useful in some cases
=> Add .waitingFor() to DockerComposeContainer

README.md, build.sbt, core/src/main/scala/com/dimafeng/testcontainers/Container.scala, modules/cockroachdb/src/main/scala/com/dimafeng/testcontainers/CockroachContainer.scala, modules/couchbase/src/main/scala/com/dimafeng/testcontainers/CouchbaseContainer.scala, modules/db2/src/main/scala/com/dimafeng/testcontainers/Db2Container.scala, modules/jdbc/src/main/scala/com/dimafeng/testcontainers/JdbcDatabaseContainer.scala, modules/mariadb/src/main/scala/com/dimafeng/testcontainers/MariaDBContainer.scala, modules/mongodb/src/main/scala/com/dimafeng/testcontainers/MongoDBContainer.scala, modules/mssqlserver/src/main/scala/com/dimafeng/testcontainers/MSSQLServerContainer.scala, modules/mysql/src/main/scala/com/dimafeng/testcontainers/MySQLContainer.scala, modules/oracle/src/main/scala/com/dimafeng/testcontainers/OracleContainer.scala, modules/postgres/src/main/scala/com/dimafeng/testcontainers/PostgreSQLContainer.scala, modules/presto/src/main/scala/com/dimafeng/testcontainers/PrestoContainer.scala, modules/rabbitmq/src/main/scala/com/dimafeng/testcontainers/RabbitMQContainer.scala, modules/solr/src/main/scala/com/dimafeng/testcontainers/SolrContainer.scala, project/Dependencies.scala, version.sbt
All details are in the readme.
=> Updating testcontainers-java to 1.14.3

README.md
This is described in: https://github.com/testcontainers/testcontainers-scala/issues/123
=> Add instruction to set fork to true.

project/Dependencies.scala
See https://github.com/testcontainers/testcontainers-java/issues/3574. Fixes issues with missing ryuk docker image.
=> Update test containers version

README.md, build.sbt, modules/trino/src/main/scala/com/dimafeng/testcontainers/TrinoContainer.scala, project/Dependencies.scala
`Presto` is deprecated now: https://www.testcontainers.org/modules/databases/presto/
=> Add Trino module

core/src/main/scala/com/dimafeng/testcontainers/DockerComposeContainer.scala
This PR contains the following:
- Add `service` option to `DockerComposeContainer`. This is to run only specific service on compose file. By default, all services are ran.
When this `docker-compose.yml` file is given,
```
services:
app:
image: java
mysql:
image: custom-mysql-image
redis:
image: custom-redis-image
```
and `app` service is not necessary for test, write as below.
```
val container = DockerComposeContainer(
composeFiles = "path/to/docker-compose.yml",
services = Services.Specific(Seq(Service("mysql", "redis")),
exposedServices = Seq(ExposedService("mysql", 3306), ExposedService("redis", 6379)),
...
)
```
=> Start specific container service when using docker compose

modules/kafka/src/main/scala/com/dimafeng/testcontainers/SchemaRegistryContainer.scala, modules/kafka/src/test/scala/com/dimafeng/testcontainers/integration/SchemaRegistrySpec.scala
Fixes #182
Thanks to @mikhailchuryakov from who I got the base for this
=> Add schema registry container

.github/workflows/test.yml
@dimafeng Let's begin by just updating this and see if tests still pass
=> Update JDK distro used in CI

README.md, modules/gcloud/src/main/scala/com/dimafeng/testcontainers/PubSubEmulatorContainer.scala, modules/gcloud/src/test/scala/com/dimafeng/testcontainers/PubSubEmulatorContainerSpec.scala, project/Dependencies.scala
Added a new test container for Google Pub/Sub emulator.
As this is my first contribution to this repo, let me know if there are any guidelines I need to follow.
Ready for review.
=> Add PubSubEmulatorContainer

project/Dependencies.scala
Release notes: https://github.com/testcontainers/testcontainers-java/releases/tag/1.17.3
=> Bump testcontainers-java 1.17.3

build.sbt, project/Plugins.sbt, project/build.properties, version.sbt
updating build.sbt, and the sbt-release plugin, see [sbt-release is now in the SBT organization](https://github.com/gseitz/sbt-release#the-canonical-repository-for-sbt-release-is-now-in-the-sbt-organization)
=> updates to sbt-release, sbt, build.sbt

project/Dependencies.scala
Align with upstream
https://github.com/testcontainers/testcontainers-java/blob/1.19.0/modules/clickhouse/build.gradle#L8
=> Bump clickhouse-jdbc 0.3.2

build.sbt, docs/src/main/tut/setup.md, modules/redis/src/main/scala/com/dimafeng/testcontainers/RedisContainer.scala, modules/redis/src/test/scala/com/dimafeng/testcontainers/RedisSpec.scala, project/Dependencies.scala
adds wrapper for [testcontainers-redis](https://github.com/redis-developer/testcontainers-redis)
=> add RedisContainer wrapper

core/src/main/scala/com/dimafeng/testcontainers/Container.scala
=> add firstMappedPort method

build.sbt, modules/milvus/src/main/scala/com/dimafeng/testcontainers/MilvusContainer.scala, modules/milvus/src/test/scala/com/dimafeng/testcontainers/MilvusSpec.scala, project/Dependencies.scala
-  update testcontainers version to 1.19.8
- add wrapper for Milvus
=> add MilvusContainer wrapper,  update testcontainers version

build.sbt, modules/quadrant/src/main/scala/com/dimafeng/testcontainers/QdrantContainer.scala, modules/quadrant/src/test/scala/com/dimafeng/testcontainers/QdrantSpec.scala, project/Dependencies.scala
=> Add QdrantContainer wrapper

build.sbt, docs/src/main/tut/setup.md, modules/k3s/src/main/scala/com/dimafeng/testcontainers/K3sContainer.scala, modules/k3s/src/test/scala/com/dimafeng/testcontainers/K3sSpec.scala, project/Dependencies.scala
=> K3S Module

project/Dependencies.scala
Reverts testcontainers/testcontainers-scala#264
=> Revert "Use AWS auth dependency for LocalStack"
